package com.example.demo.entity;

import jakarta.persistence.*;
import lombok.*;

@AllArgsConstructor
@NoArgsConstructor
@Entity
@Data
@Table(name = "students")
public class Student {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;

    @Column(name = "student_name", nullable = false)
    private String studentName;

    @Column(name = "email", nullable = false)
    private String email;

    @Column(name = "student_gender")
    private String studentGender;

    @Column(name = "student_age")
    private int studentAge;

    @Column(name = "student_address", nullable = false)
    private String studentAddress;

    @Column(name = "username", nullable = false, unique = true)
    private String username;

    @Column(name = "password", nullable = false)
    private String password;

    // Constructor without ID for creating new students
    public Student(String studentName, String email, String studentGender, int studentAge, String studentAddress, String username, String password) {
        this.studentName = studentName;
        this.email = email;
        this.studentGender = studentGender;
        this.studentAge = studentAge;
        this.studentAddress = studentAddress;
        this.username = username;
        this.password = password;
    }

    // Getters and setters are automatically generated by Lombok
}
